sudo: required
services:
  - docker

before_install:
  - docker build -t rajeshemailto/docker-react -f Dockerfile.dev .


script:
  - docker run rajeshemailto/docker-react npm run test -- --coverage 

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-660012216174"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  access_access_key:
    secure: "$AWS_SECRET"
